version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lead_app_db
      - POSTGRES_USER=lead_app_admin
      - POSTGRES_PASSWORD=lead_pass
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    container_name: backend
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app  # Mount backend code into the container
      - ./backend/logs:/usr/src/app/logs  # Mount logs directory into the container
    depends_on:
      - db
      - redis
    environment:
      - ENVIRONMENT=prod

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount frontend code into the container

volumes:
  postgres_data:
