# POST http://127.0.0.1:8000/api/accounts/profile/ HTTP/1.1
# content-type: application/json

# {
#     "username": "abc@gmail.com",
#     "password": "mailman"
# }

POST http://127.0.0.1:8000/api/scraper/generate/ HTTP/1.1
content-type: application/json
Authorization: Token 75f0db6efe1709248288bcfbcc587bcd67de4b7e1d0584a7c69322ec4ab01aeb
Connection: keep-alive

{
    "username": "magicmusicsquad",
    "tags": "",
    "allTagsCheckbox": false,
    "min_likes": 1000,
    "max_likes": 10000000,
    "date": "2015-01-01",
    "leads": 20
}