# Generated by Django 5.0.4 on 2024-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingtask",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
