# Generated by Django 5.0.4 on 2024-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_scrapingtask_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="email",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="phone",
        ),
        migrations.AlterField(
            model_name="lead",
            name="spotify_username",
            field=models.JSONField(),
        ),
    ]
