# Generated by Django 5.0.4 on 2024-06-17 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_remove_lead_email_remove_lead_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                size=None,
            ),
        ),
    ]
