name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Docker cache
      uses: actions/cache@v3
      with:
        path: ~/.docker/dch
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v2  # Optional for advanced builds

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/lead-generation-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/lead-generation-app:latest

    - name: Deploy to DigitalOcean Droplet via SSH (improved security)
      uses: appleboy/ssh-action@v1  # Updated to latest version
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DEPLOY_USER }}  # Don't use root for deployments
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/lead-generation-app:latest
          docker stop lead-generation-app || true
          docker rm lead_generation-app || true
          docker run -d --name lead-generation-app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/lead-generation-app:latest

